var name1 = "apple";
var name2 = "apple";
var result1 = name1 == name2 ? true : false;
console.log(result1);
var Capital1 = "apple";
var Capital2 = "Apple";
var result2 = Capital1 == Capital2 ? true : false;
console.log(result2);
var CheckNum1 = 7;
var CheckNum2 = 5;
var result3 = CheckNum1 >= CheckNum2 ? true : false;
console.log(result3);
var OR1 = 12;
var OR2 = 22;
var result4 = OR1 > OR2 || OR1 <= 8 ? true : false;
console.log(result4);
var And1 = 7;
var And2 = 5;
var result5 = And1 > And2 && And1 <= 8 ? true : false;
console.log(result5);
var List1 = ["Mannan"];
var result6 = List1 == null ? true : false;
console.log(result6);
var List2 = [];
var result7 = List2.length === 0 ? true : false;
console.log(result7);
