console.log("%%%%%True Statements%%%%%");
var car1 = "Sonata";
console.log(car1 == "Sonata");
var car2 = "Sportage";
console.log(car2 == "Sportage");
var car3 = "Tesla";
console.log(car3 == "Tesla");
var car4 = "Lamborghini";
console.log(car4 == "Lamborghini");
var car5 = "Civic";
console.log(car5 == "Civic");
console.log("%%%%%False Statements%%%%%");
var car6 = "Sonat";
console.log(car6 == "Sonata");
var car7 = "Sportag";
console.log(car7 == "Sportage");
var car8 = "Tesl";
console.log(car8 == "Tesla");
var car9 = "Lamborghin";
console.log(car9 == "Lamborghini");
var car10 = "Civi";
console.log(car10 == "Civic");
